name: master

on:
  push:
    paths-ignore:
      - 'doc/**'
      - '*.md'
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout the repo
        uses: actions/checkout@v3

      - uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: "temurin"

      - name: run tests
        run: ./gradlew check

      - name: deploy snapshot
        run: ./gradlew publishToMavenCentral

      - name: bundle the build report
        if: ${{ !cancelled() }}       # run this step even if the previous step failed
        run: find . -type d -name 'reports' | zip -@ -r build-reports.zip

      - name: upload the build report
        if: ${{ !cancelled() }}       # run this step even if the previous step failed
        uses: actions/upload-artifact@master
        with:
          name: error-report
          path: build-reports.zip

      - name: Test Report
        uses: dorny/test-reporter@v2
        if: ${{ !cancelled() }}       # run this step even if the previous step failed
        with:
          name: Kotest Tests          # Name of the check run which will be created
          path: build/test-reports/*.xml    # Path to test results
          reporter: java-junit        # Format of test results

env:
  GRADLE_OPTS: -Dorg.gradle.configureondemand=true -Dorg.gradle.parallel=false -Dorg.gradle.jvmargs="-Xmx3g -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8"
  ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.OSSRH_USERNAME }}
  ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.OSSRH_PASSWORD }}
  ORG_GRADLE_PROJECT_signingInMemoryKey: ${{ secrets.SIGNING_KEY }}
  ORG_GRADLE_PROJECT_signingInMemoryKeyPassword: ${{ secrets.SIGNING_PASSWORD }}
